"use client";
import { Inter } from "next/font/google";
import "@/app/styles/globals.css";
import Header from "../components/Header/Header";
import Head from "next/head";
import { Provider } from "react-redux";
import { store } from "@/redux/store";
// import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <body className={inter.className}>
        <Header />
        <div>
          <Provider store={store}>{children}</Provider>
        </div>
      </body>
    </html>
  );
}

export default RootLayout;
